export * from './types'
export { SIGNALS, SIGNAL_IDS, formatValue, formatWithUnit } from './signals'
export { analyseSeries, hoursBetween } from './analytics'
export { assessPatient, assessWard, latestObservationTime, severityRank } from './engine'
export { describeFinding, wardHeadline, relativeTime, formatHours, SEVERITY_LABEL, TRAJECTORY_LABEL, HORIZON_LABEL } from './language'
export type { FindingText } from './language'
export { IMPORTANCE_WEIGHTS, SEVERITY_THRESHOLDS, ANALYSIS_CONFIG } from './config'
